services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: banking_api
      POSTGRES_USER: banking_user
      POSTGRES_PASSWORD: banking_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banking_user -d banking_api"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
